defmodule LLMDB.Application do
  @moduledoc """
  OTP Application for LLMDB.

  Automatically loads the pre-built snapshot on application start.
  The snapshot is generated by `mix llm_db.build` and packaged
  with the release.
  """

  use Application

  @impl true
  def start(_type, _args) do
    # Load .env file if it exists
    load_dotenv()

    # Ensure modality atoms exist before loading snapshot
    _ = LLMDB.Generated.ValidModalities.list()

    # Ensure provider atoms exist before loading snapshot
    _ = LLMDB.Generated.ValidProviders.list()

    if Application.get_env(:llm_db, :skip_packaged_load, false) do
      {:ok, self()}
    else
      case LLMDB.load() do
        {:ok, _snapshot} ->
          {:ok, self()}

        {:error, reason} ->
          {:error, reason}
      end
    end
  end

  defp load_dotenv do
    env_path = Path.join(File.cwd!(), ".env")

    if File.exists?(env_path) and not File.dir?(env_path) do
      vars = Dotenvy.source!(env_path)
      System.put_env(vars)
    end
  end
end
